name: ASPA_Framework
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - scipy
  - notebook 
  - gdal
  - netCDF4
  - flopy
  - rasterio
  - fiona
  - pyshp
  - scikit-learn
  - lmfit
  - xlrd
  - geopandas
  - descartes
